#!/bin/zsh

echo "  ____ ___  _   _ _____     "
echo " / ___/ _ \| \ | |  ___|    "
echo "| |  | | | |  \| | |_       "
echo "| |__| |_| | |\  |  _|      "
echo " \____\___/|_| \_|_|        "

location=$(pwd)
alias_file=".zshrc.pre-oh-my-zsh"
dependencies=$location/dependencies

cd $HOME

if [[ -f $alias_file ]]; then echo "All the stuff already exists... Exit..."; cd -; fi
if ! [[ -z $(cat .zshrc | grep 'oh-my-zsh') ]]; then echo "All the staff already exists... Exit..."; cd -; fi

# Install HOMEBREW
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo "export PATH=/opt/homebrew/bin/:$PATH" >> .zshrc

ln -s $location/.bash_profile .zshrc
source .zshrc

read "psqlInstall?Do you want to install psql and start it service?"
if [[ $psqlInstall == "y" || $psqlInstall == "Y" ]]; then
    brew install postgresql
fi

# Plugins.....
echo "\n"
read "opt?Do you want to install all the plugins? // y|Y \n"
if [[ $opt == "y" || $opt == "Y" ]]; then 
    cd $dependencies 
    ./install
    cd -
fi 
